---
- apt:
    update_cache: yes

- name: "Install rtr-server {{rtr_server_deb_package_url}}"
  apt:
    deb: "{{rtr_server_deb_package_url}}"

- name: "Install validator {{validator_3_deb_package_url}}"
  apt:
    deb: "{{validator_3_deb_package_url}}"

- name: Make sure rpki-validator listens on all ips
  lineinfile:
    path: /etc/rpki-validator-3/application.properties
    regexp: '^listen='
    line: server.address=0.0.0.0

- name: Make sure rtr-server listens on all ips
  lineinfile:
    path: /etc/rpki-rtr-server/application.properties
    regexp: '^server.address='
    line: server.address=0.0.0.0
  notify: restart rpki-rtr-server


- name: Make sure rpki-validator listens on all ips
  lineinfile:
    path: /etc/rpki-validator-3/application.properties
    regexp: '^server.address='
    line: server.address=0.0.0.0
  notify: restart rpki-validator-3

- name: Enable rpki-validator-3 service
  systemd:
    name: rpki-validator-3
    enabled: yes
    state: started

- name: Enable rtr-server service
  systemd:
    name: rpki-rtr-server
    enabled: yes
    state:  started
