---
- name: Add yum repo
  yum_repository:
    name: ripencc-rpki-rc
    description: RIPE NCC RPKI Validator 3 RELEASE CANDIDATE releases
    baseurl: "{{rpki.centos_repo_url}}"
    
- name: Update repositories cache
  yum:
    state: present
    update_cache: yes

- name: Upgrade all packages to the latest version
  yum:
    name: "*"
    state: latest

- name: Install packages
  yum:
    disable_gpg_check: True
    name:
      - rpki-validator
      - rpki-rtr-server

- name: Make sure rtr-server listens on all ips
  lineinfile:
    path: /etc/rpki-rtr-server/application.properties
    regexp: '^server.address='
    line: server.address=0.0.0.0
  notify: restart rpki-rtr-server

- name: Make sure rtr-server listens on all ips
  lineinfile:
    path: /etc/rpki-rtr-server/application.properties
    regexp: '^rtr.server.address='
    line: rtr.server.address=0.0.0.0
  notify: restart rpki-rtr-server
    
- name: Make sure rpki-validator listens on all ips
  lineinfile:
    path: /etc/rpki-validator-3/application.properties
    regexp: '^server.address='
    line: server.address=0.0.0.0
  notify: restart rpki-validator-3
    
- name: Enable rpki-validator-3 service
  systemd:
    name: rpki-validator-3
    enabled: yes
    state: started
    
- name: Enable rtr-server service
  systemd:
    name: rpki-rtr-server
    enabled: yes
    state:  started

- name: Download ARIN tal
  get_url:
    url: "{{item}}"
    dest: "/var/lib/rpki-validator-3/preconfigured-tals/{{item | basename}}"
    owner: rpki
    group: rpki
    mode: 0644
  notify: restart rpki-validator-3
  loop:
    - https://www.arin.net/resources/manage/rpki/arin-ripevalidator.tal

- name: Download tals
  get_url:
    url: "{{item}}"
    dest: "/var/lib/rpki-validator-3/preconfigured-tals/{{item | basename}}"
    owner: rpki
    group: rpki
    mode: 0644
  notify: restart rpki-validator-3
  loop:
    - https://rpki-testbed.apnic.net/repository/apnic-rpki-root-iana-origin.tal
  when: "{{rpki.all_tals | default(True) }}"

- name: Add tals from files
  copy:
    src: "{{item}}"
    dest: "/var/lib/rpki-validator-3/preconfigured-tals/{{item}}"
    owner: rpki
    group: rpki
    mode: 0644
  notify: restart rpki-validator-3
  loop:
    - apnic-as0.tal
    - RIPE-NCC-Pilot.tal
  when: "{{rpki.all_tals | default(True) }}"
