---
- name: Install firewalld python bindings
  yum:
    name:
      - firewalld
      - python3-firewall

- name: Open ports in firewall
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
  loop:
    - "8081/tcp"
    - "8080/tcp"
    - "8323/tcp"
