---
- name: Install epel
  yum:
    name: epel-release

- name: Add repository
  yum_repository:
    name: epel-testing
    description: Extra Packages for Enterprise Linux $releasever - Testing - $basearch
    baseurl: https://download.fedoraproject.org/pub/epel/testing/$releasever/Everything/$basearch
    metalink: https://mirrors.fedoraproject.org/metalink?repo=testing-epel$releasever&arch=$basearch&infra=$infra&content=$contentdir
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
    
- name: Update repositories cache
  yum:
    state: present
    update_cache: yes

- name: Install rpki-client
  package:
    name:
      - rpki-client
