---
- import_tasks: setup_centos.yml
  when: ansible_distribution == 'CentOS'
    
- name: Update repositories cache
  yum:
    state: present
    update_cache: yes


- name: Install rpki-client
  package:
    name:
      - rpki-client
